development:
  adapter: postgresql
  encoding: utf8
  database: hackbikeshare_development
  pool: 5
  username: 
  password:

test: 
  adapter: postgresql
  encoding: utf8
  database: hackbikeshare_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: hackbikeshare_production
  pool: 5
  username: 
  password:
