# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1947472aaecf9f0e742df95430c1029f39783d60d216c3a231d4e2694f0ea51ef124b794b40a5c1694a03a9bb21556329cb0f0a8b27c6bf34b36c2c21be06b6

test:
  secret_key_base: b005779df30583c8b36dd10a305878acfade0593702ba53b6b4098099c0f4117a0ca944d58926aaa09ae2454dc412cca62a78376710df87363ab3eace9109960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
